# fly.toml app configuration file generated for skillworkshop on 2023-10-31T11:10:07+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "skillworkshop"
primary_region = "arn"

[build]
  image = "akorkh/skillworkshop:latest"

[env]
  ASPNETCORE_URLS = "http://+:8080"
  Cloudinary__ApiKey = "917531996741457"
  Cloudinary__CloudName = "dqtgl2rlu"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
